# Generated by Django 4.2 on 2023-07-24 20:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=200)),
                ('comment_body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=99999999999, null=True)),
                ('slug', models.SlugField(blank=True, max_length=999999999, null=True, verbose_name='Слаг')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='post/%Y%m/%d')),
                ('status', models.CharField(blank=True, choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=2, null=True)),
                ('publish', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Видео')),
                ('time', models.CharField(blank=True, max_length=9999900, null=True, verbose_name='Премьера')),
                ('time_one', models.CharField(blank=True, max_length=9999900, null=True, verbose_name='Время')),
                ('time_two', models.CharField(blank=True, max_length=9999900, null=True, verbose_name='Режиссер')),
                ('time_on', models.CharField(blank=True, max_length=9999900, null=True, verbose_name='Кинопрокат')),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='post_post_publish_2758a7_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
        ),
    ]
