# Generated by Django 4.2 on 2023-07-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_pro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pro',
        ),
    ]
